---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
    - name: Reboot
      reboot:

    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present

    - name: Add APT repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install mongodb package
      apt:
        name: mongodb-org
        state: present

    - name: Configure service supervisor
      systemd:
        name: mongod
        enabled: yes
